// Code generated by go-swagger; DO NOT EDIT.

package issues

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewIssueGetParams creates a new IssueGetParams object
// with the default values initialized.
func NewIssueGetParams() *IssueGetParams {
	var ()
	return &IssueGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewIssueGetParamsWithTimeout creates a new IssueGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewIssueGetParamsWithTimeout(timeout time.Duration) *IssueGetParams {
	var ()
	return &IssueGetParams{

		timeout: timeout,
	}
}

// NewIssueGetParamsWithContext creates a new IssueGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewIssueGetParamsWithContext(ctx context.Context) *IssueGetParams {
	var ()
	return &IssueGetParams{

		Context: ctx,
	}
}

// NewIssueGetParamsWithHTTPClient creates a new IssueGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewIssueGetParamsWithHTTPClient(client *http.Client) *IssueGetParams {
	var ()
	return &IssueGetParams{
		HTTPClient: client,
	}
}

/*IssueGetParams contains all the parameters to send to the API endpoint
for the issue get operation typically these are written to a http.Request
*/
type IssueGetParams struct {

	/*ID
	  The issue id.

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the issue get params
func (o *IssueGetParams) WithTimeout(timeout time.Duration) *IssueGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the issue get params
func (o *IssueGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the issue get params
func (o *IssueGetParams) WithContext(ctx context.Context) *IssueGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the issue get params
func (o *IssueGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the issue get params
func (o *IssueGetParams) WithHTTPClient(client *http.Client) *IssueGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the issue get params
func (o *IssueGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the issue get params
func (o *IssueGetParams) WithID(id int64) *IssueGetParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the issue get params
func (o *IssueGetParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *IssueGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param id
	qrID := o.ID
	qID := swag.FormatInt64(qrID)
	if qID != "" {
		if err := r.SetQueryParam("id", qID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
