// Code generated by go-swagger; DO NOT EDIT.

package issues

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/UNO-SOFT/mantis-rest/models"
)

// NewIssueNoteAddParams creates a new IssueNoteAddParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewIssueNoteAddParams() *IssueNoteAddParams {
	return &IssueNoteAddParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewIssueNoteAddParamsWithTimeout creates a new IssueNoteAddParams object
// with the ability to set a timeout on a request.
func NewIssueNoteAddParamsWithTimeout(timeout time.Duration) *IssueNoteAddParams {
	return &IssueNoteAddParams{
		timeout: timeout,
	}
}

// NewIssueNoteAddParamsWithContext creates a new IssueNoteAddParams object
// with the ability to set a context for a request.
func NewIssueNoteAddParamsWithContext(ctx context.Context) *IssueNoteAddParams {
	return &IssueNoteAddParams{
		Context: ctx,
	}
}

// NewIssueNoteAddParamsWithHTTPClient creates a new IssueNoteAddParams object
// with the ability to set a custom HTTPClient for a request.
func NewIssueNoteAddParamsWithHTTPClient(client *http.Client) *IssueNoteAddParams {
	return &IssueNoteAddParams{
		HTTPClient: client,
	}
}

/*
IssueNoteAddParams contains all the parameters to send to the API endpoint

	for the issue note add operation.

	Typically these are written to a http.Request.
*/
type IssueNoteAddParams struct {

	/* Body.

	   The note to add.
	*/
	Body *models.CreateNoteResponse

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the issue note add params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IssueNoteAddParams) WithDefaults() *IssueNoteAddParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the issue note add params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IssueNoteAddParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the issue note add params
func (o *IssueNoteAddParams) WithTimeout(timeout time.Duration) *IssueNoteAddParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the issue note add params
func (o *IssueNoteAddParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the issue note add params
func (o *IssueNoteAddParams) WithContext(ctx context.Context) *IssueNoteAddParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the issue note add params
func (o *IssueNoteAddParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the issue note add params
func (o *IssueNoteAddParams) WithHTTPClient(client *http.Client) *IssueNoteAddParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the issue note add params
func (o *IssueNoteAddParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the issue note add params
func (o *IssueNoteAddParams) WithBody(body *models.CreateNoteResponse) *IssueNoteAddParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the issue note add params
func (o *IssueNoteAddParams) SetBody(body *models.CreateNoteResponse) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *IssueNoteAddParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
