// Code generated by go-swagger; DO NOT EDIT.

package issues

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/UNO-SOFT/mantis-rest/models"
)

// NewIssueAddFileParams creates a new IssueAddFileParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewIssueAddFileParams() *IssueAddFileParams {
	return &IssueAddFileParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewIssueAddFileParamsWithTimeout creates a new IssueAddFileParams object
// with the ability to set a timeout on a request.
func NewIssueAddFileParamsWithTimeout(timeout time.Duration) *IssueAddFileParams {
	return &IssueAddFileParams{
		timeout: timeout,
	}
}

// NewIssueAddFileParamsWithContext creates a new IssueAddFileParams object
// with the ability to set a context for a request.
func NewIssueAddFileParamsWithContext(ctx context.Context) *IssueAddFileParams {
	return &IssueAddFileParams{
		Context: ctx,
	}
}

// NewIssueAddFileParamsWithHTTPClient creates a new IssueAddFileParams object
// with the ability to set a custom HTTPClient for a request.
func NewIssueAddFileParamsWithHTTPClient(client *http.Client) *IssueAddFileParams {
	return &IssueAddFileParams{
		HTTPClient: client,
	}
}

/*
IssueAddFileParams contains all the parameters to send to the API endpoint

	for the issue add file operation.

	Typically these are written to a http.Request.
*/
type IssueAddFileParams struct {

	// Files.
	Files []*models.FileRef

	/* ID.

	   The issue to attach to.

	   Format: int64
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the issue add file params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IssueAddFileParams) WithDefaults() *IssueAddFileParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the issue add file params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IssueAddFileParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the issue add file params
func (o *IssueAddFileParams) WithTimeout(timeout time.Duration) *IssueAddFileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the issue add file params
func (o *IssueAddFileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the issue add file params
func (o *IssueAddFileParams) WithContext(ctx context.Context) *IssueAddFileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the issue add file params
func (o *IssueAddFileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the issue add file params
func (o *IssueAddFileParams) WithHTTPClient(client *http.Client) *IssueAddFileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the issue add file params
func (o *IssueAddFileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFiles adds the files to the issue add file params
func (o *IssueAddFileParams) WithFiles(files []*models.FileRef) *IssueAddFileParams {
	o.SetFiles(files)
	return o
}

// SetFiles adds the files to the issue add file params
func (o *IssueAddFileParams) SetFiles(files []*models.FileRef) {
	o.Files = files
}

// WithID adds the id to the issue add file params
func (o *IssueAddFileParams) WithID(id int64) *IssueAddFileParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the issue add file params
func (o *IssueAddFileParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *IssueAddFileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Files != nil {
		if err := r.SetBodyParam(o.Files); err != nil {
			return err
		}
	}

	// query param id
	qrID := o.ID
	qID := swag.FormatInt64(qrID)
	if qID != "" {

		if err := r.SetQueryParam("id", qID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
