// Code generated by go-swagger; DO NOT EDIT.

package issues

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewIssueGetParams creates a new IssueGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewIssueGetParams() *IssueGetParams {
	return &IssueGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewIssueGetParamsWithTimeout creates a new IssueGetParams object
// with the ability to set a timeout on a request.
func NewIssueGetParamsWithTimeout(timeout time.Duration) *IssueGetParams {
	return &IssueGetParams{
		timeout: timeout,
	}
}

// NewIssueGetParamsWithContext creates a new IssueGetParams object
// with the ability to set a context for a request.
func NewIssueGetParamsWithContext(ctx context.Context) *IssueGetParams {
	return &IssueGetParams{
		Context: ctx,
	}
}

// NewIssueGetParamsWithHTTPClient creates a new IssueGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewIssueGetParamsWithHTTPClient(client *http.Client) *IssueGetParams {
	return &IssueGetParams{
		HTTPClient: client,
	}
}

/*
IssueGetParams contains all the parameters to send to the API endpoint

	for the issue get operation.

	Typically these are written to a http.Request.
*/
type IssueGetParams struct {

	/* ID.

	   The issue id.

	   Format: int64
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the issue get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IssueGetParams) WithDefaults() *IssueGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the issue get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IssueGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the issue get params
func (o *IssueGetParams) WithTimeout(timeout time.Duration) *IssueGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the issue get params
func (o *IssueGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the issue get params
func (o *IssueGetParams) WithContext(ctx context.Context) *IssueGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the issue get params
func (o *IssueGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the issue get params
func (o *IssueGetParams) WithHTTPClient(client *http.Client) *IssueGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the issue get params
func (o *IssueGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the issue get params
func (o *IssueGetParams) WithID(id int64) *IssueGetParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the issue get params
func (o *IssueGetParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *IssueGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param id
	qrID := o.ID
	qID := swag.FormatInt64(qrID)
	if qID != "" {

		if err := r.SetQueryParam("id", qID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
