// Code generated by go-swagger; DO NOT EDIT.

package localization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/UNO-SOFT/mantis-rest/models"
)

// LangGetReader is a Reader for the LangGet structure.
type LangGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LangGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLangGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewLangGetForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewLangGetServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewLangGetOK creates a LangGetOK with default headers values
func NewLangGetOK() *LangGetOK {
	return &LangGetOK{}
}

/*LangGetOK handles this case with default header values.

Success
*/
type LangGetOK struct {
	Payload *models.LangGetResponse
}

func (o *LangGetOK) Error() string {
	return fmt.Sprintf("[GET /lang][%d] langGetOK  %+v", 200, o.Payload)
}

func (o *LangGetOK) GetPayload() *models.LangGetResponse {
	return o.Payload
}

func (o *LangGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LangGetResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLangGetForbidden creates a LangGetForbidden with default headers values
func NewLangGetForbidden() *LangGetForbidden {
	return &LangGetForbidden{}
}

/*LangGetForbidden handles this case with default header values.

Access denied
*/
type LangGetForbidden struct {
}

func (o *LangGetForbidden) Error() string {
	return fmt.Sprintf("[GET /lang][%d] langGetForbidden ", 403)
}

func (o *LangGetForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewLangGetServiceUnavailable creates a LangGetServiceUnavailable with default headers values
func NewLangGetServiceUnavailable() *LangGetServiceUnavailable {
	return &LangGetServiceUnavailable{}
}

/*LangGetServiceUnavailable handles this case with default header values.

Mantis Offline
*/
type LangGetServiceUnavailable struct {
}

func (o *LangGetServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /lang][%d] langGetServiceUnavailable ", 503)
}

func (o *LangGetServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
