// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUserGetMeParams creates a new UserGetMeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUserGetMeParams() *UserGetMeParams {
	return &UserGetMeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUserGetMeParamsWithTimeout creates a new UserGetMeParams object
// with the ability to set a timeout on a request.
func NewUserGetMeParamsWithTimeout(timeout time.Duration) *UserGetMeParams {
	return &UserGetMeParams{
		timeout: timeout,
	}
}

// NewUserGetMeParamsWithContext creates a new UserGetMeParams object
// with the ability to set a context for a request.
func NewUserGetMeParamsWithContext(ctx context.Context) *UserGetMeParams {
	return &UserGetMeParams{
		Context: ctx,
	}
}

// NewUserGetMeParamsWithHTTPClient creates a new UserGetMeParams object
// with the ability to set a custom HTTPClient for a request.
func NewUserGetMeParamsWithHTTPClient(client *http.Client) *UserGetMeParams {
	return &UserGetMeParams{
		HTTPClient: client,
	}
}

/*
UserGetMeParams contains all the parameters to send to the API endpoint

	for the user get me operation.

	Typically these are written to a http.Request.
*/
type UserGetMeParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the user get me params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UserGetMeParams) WithDefaults() *UserGetMeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the user get me params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UserGetMeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the user get me params
func (o *UserGetMeParams) WithTimeout(timeout time.Duration) *UserGetMeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the user get me params
func (o *UserGetMeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the user get me params
func (o *UserGetMeParams) WithContext(ctx context.Context) *UserGetMeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the user get me params
func (o *UserGetMeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the user get me params
func (o *UserGetMeParams) WithHTTPClient(client *http.Client) *UserGetMeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the user get me params
func (o *UserGetMeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *UserGetMeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
