// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new users API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for users API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	UserGetMe(params *UserGetMeParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UserGetMeOK, error)

	UserResetPassword(params *UserResetPasswordParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UserResetPasswordOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
UserGetMe gets information about logged in user

Gets information about logged in user.
*/
func (a *Client) UserGetMe(params *UserGetMeParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UserGetMeOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUserGetMeParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "userGetMe",
		Method:             "GET",
		PathPattern:        "/users/me",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &UserGetMeReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UserGetMeOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for userGetMe: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
UserResetPassword resets user s password

Reset the user's password
*/
func (a *Client) UserResetPassword(params *UserResetPasswordParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UserResetPasswordOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUserResetPasswordParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "userResetPassword",
		Method:             "PUT",
		PathPattern:        "/users/reset",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &UserResetPasswordReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UserResetPasswordOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for userResetPassword: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
