// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUserResetPasswordParams creates a new UserResetPasswordParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUserResetPasswordParams() *UserResetPasswordParams {
	return &UserResetPasswordParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUserResetPasswordParamsWithTimeout creates a new UserResetPasswordParams object
// with the ability to set a timeout on a request.
func NewUserResetPasswordParamsWithTimeout(timeout time.Duration) *UserResetPasswordParams {
	return &UserResetPasswordParams{
		timeout: timeout,
	}
}

// NewUserResetPasswordParamsWithContext creates a new UserResetPasswordParams object
// with the ability to set a context for a request.
func NewUserResetPasswordParamsWithContext(ctx context.Context) *UserResetPasswordParams {
	return &UserResetPasswordParams{
		Context: ctx,
	}
}

// NewUserResetPasswordParamsWithHTTPClient creates a new UserResetPasswordParams object
// with the ability to set a custom HTTPClient for a request.
func NewUserResetPasswordParamsWithHTTPClient(client *http.Client) *UserResetPasswordParams {
	return &UserResetPasswordParams{
		HTTPClient: client,
	}
}

/*
UserResetPasswordParams contains all the parameters to send to the API endpoint

	for the user reset password operation.

	Typically these are written to a http.Request.
*/
type UserResetPasswordParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the user reset password params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UserResetPasswordParams) WithDefaults() *UserResetPasswordParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the user reset password params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UserResetPasswordParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the user reset password params
func (o *UserResetPasswordParams) WithTimeout(timeout time.Duration) *UserResetPasswordParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the user reset password params
func (o *UserResetPasswordParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the user reset password params
func (o *UserResetPasswordParams) WithContext(ctx context.Context) *UserResetPasswordParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the user reset password params
func (o *UserResetPasswordParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the user reset password params
func (o *UserResetPasswordParams) WithHTTPClient(client *http.Client) *UserResetPasswordParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the user reset password params
func (o *UserResetPasswordParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *UserResetPasswordParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
