// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/UNO-SOFT/mantis-rest/models"
)

// UserGetMeReader is a Reader for the UserGetMe structure.
type UserGetMeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserGetMeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUserGetMeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewUserGetMeForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewUserGetMeServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUserGetMeOK creates a UserGetMeOK with default headers values
func NewUserGetMeOK() *UserGetMeOK {
	return &UserGetMeOK{}
}

/*UserGetMeOK handles this case with default header values.

Success
*/
type UserGetMeOK struct {
	Payload *models.UserMeResponse
}

func (o *UserGetMeOK) Error() string {
	return fmt.Sprintf("[GET /users/me][%d] userGetMeOK  %+v", 200, o.Payload)
}

func (o *UserGetMeOK) GetPayload() *models.UserMeResponse {
	return o.Payload
}

func (o *UserGetMeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserMeResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUserGetMeForbidden creates a UserGetMeForbidden with default headers values
func NewUserGetMeForbidden() *UserGetMeForbidden {
	return &UserGetMeForbidden{}
}

/*UserGetMeForbidden handles this case with default header values.

Access denied
*/
type UserGetMeForbidden struct {
}

func (o *UserGetMeForbidden) Error() string {
	return fmt.Sprintf("[GET /users/me][%d] userGetMeForbidden ", 403)
}

func (o *UserGetMeForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUserGetMeServiceUnavailable creates a UserGetMeServiceUnavailable with default headers values
func NewUserGetMeServiceUnavailable() *UserGetMeServiceUnavailable {
	return &UserGetMeServiceUnavailable{}
}

/*UserGetMeServiceUnavailable handles this case with default header values.

Mantis Offline
*/
type UserGetMeServiceUnavailable struct {
}

func (o *UserGetMeServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /users/me][%d] userGetMeServiceUnavailable ", 503)
}

func (o *UserGetMeServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
