// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateNoteResponse create note response
//
// swagger:model CreateNoteResponse
type CreateNoteResponse struct {

	// issue
	Issue *Issue `json:"issue,omitempty"`

	// note
	Note *Note `json:"note,omitempty"`
}

// Validate validates this create note response
func (m *CreateNoteResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateIssue(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNote(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateNoteResponse) validateIssue(formats strfmt.Registry) error {
	if swag.IsZero(m.Issue) { // not required
		return nil
	}

	if m.Issue != nil {
		if err := m.Issue.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("issue")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("issue")
			}
			return err
		}
	}

	return nil
}

func (m *CreateNoteResponse) validateNote(formats strfmt.Registry) error {
	if swag.IsZero(m.Note) { // not required
		return nil
	}

	if m.Note != nil {
		if err := m.Note.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("note")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("note")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this create note response based on the context it is used
func (m *CreateNoteResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateIssue(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateNote(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateNoteResponse) contextValidateIssue(ctx context.Context, formats strfmt.Registry) error {

	if m.Issue != nil {
		if err := m.Issue.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("issue")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("issue")
			}
			return err
		}
	}

	return nil
}

func (m *CreateNoteResponse) contextValidateNote(ctx context.Context, formats strfmt.Registry) error {

	if m.Note != nil {
		if err := m.Note.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("note")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("note")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreateNoteResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateNoteResponse) UnmarshalBinary(b []byte) error {
	var res CreateNoteResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
