// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// LangGetResponse lang get response
// swagger:model LangGetResponse
type LangGetResponse struct {

	// language
	Language string `json:"language,omitempty"`

	// strings
	Strings []*LocalizedString `json:"strings"`
}

// Validate validates this lang get response
func (m *LangGetResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStrings(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LangGetResponse) validateStrings(formats strfmt.Registry) error {

	if swag.IsZero(m.Strings) { // not required
		return nil
	}

	for i := 0; i < len(m.Strings); i++ {
		if swag.IsZero(m.Strings[i]) { // not required
			continue
		}

		if m.Strings[i] != nil {
			if err := m.Strings[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("strings" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *LangGetResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LangGetResponse) UnmarshalBinary(b []byte) error {
	var res LangGetResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
