// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TimeTrackingRef time tracking ref
//
// swagger:model TimeTrackingRef
type TimeTrackingRef struct {

	// duration
	Duration string `json:"duration,omitempty"`
}

// Validate validates this time tracking ref
func (m *TimeTrackingRef) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this time tracking ref based on context it is used
func (m *TimeTrackingRef) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TimeTrackingRef) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TimeTrackingRef) UnmarshalBinary(b []byte) error {
	var res TimeTrackingRef
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
